#!/usr/bin/env python3
"""
Phonetic data for text-to-speech system.
Contains phoneme formant frequencies and word/letter mappings.
"""

# Phoneme to formant frequency mapping (approximate)
PHONEME_FORMANTS = {
    # Vowels
    "iy": (270, 2290, 3010),  # beet
    "ih": (390, 1990, 2550),  # bit
    "eh": (530, 1840, 2480),  # bet
    "ae": (660, 1720, 2410),  # bat
    "ah": (850, 1610, 2270),  # but
    "ao": (850, 1610, 2270),  # bought
    "ow": (570, 840, 2410),  # boat
    "uh": (640, 1190, 2390),  # book
    "uw": (300, 870, 2240),  # boot
    "er": (490, 1350, 1690),  # bird
    # Consonants (simplified)
    "p": (300, 800, 2200),  # pop
    "b": (200, 800, 2200),  # bob
    "t": (400, 1200, 2200),  # top
    "d": (300, 1200, 2200),  # dad
    "k": (500, 1500, 2500),  # kick
    "g": (400, 1500, 2500),  # gag
    "m": (200, 800, 2200),  # mom
    "n": (250, 900, 2300),  # nun
    "ng": (300, 800, 2200),  # sing
    "f": (400, 2000, 2500),  # fan
    "v": (200, 2000, 2500),  # van
    "s": (500, 2000, 2500),  # sip
    "z": (300, 2000, 2500),  # zip
    "sh": (400, 1800, 2500),  # ship
    "zh": (300, 1800, 2500),  # vision
    "h": (600, 1400, 2400),  # hat
    "l": (400, 1000, 2400),  # lay
    "r": (400, 1200, 2200),  # ray
    "y": (300, 2000, 2500),  # yes
    "w": (300, 800, 2200),  # wet
    # Silence
    "sil": (0, 0, 0),
}

# Word to phoneme mapping (simplified)
WORD_PHONEMES = {
    # Common words for git hooks
    "commit": ["k", "ah", "m", "ih", "t"],
    "push": ["p", "uh", "sh"],
    "git": ["g", "ih", "t"],
    "hook": ["h", "uh", "k"],
    "test": ["t", "eh", "s", "t"],
    "audio": ["ao", "d", "iy", "ow"],
    "output": ["aw", "t", "p", "uh", "t"],
    "nine": ["n", "ay", "n"],
    "inches": ["ih", "n", "ch", "ih", "z"],
    "repository": ["r", "ih", "p", "ao", "z", "ih", "t", "ao", "r", "iy"],
    "message": ["m", "eh", "s", "ih", "jh"],
    "industrial": ["ih", "n", "d", "ah", "s", "t", "r", "iy", "ah", "l"],
    "voice": ["v", "oy", "s"],
    "synthesis": ["s", "ih", "n", "th", "ah", "s", "ih", "s"],
    "successful": ["s", "ah", "k", "s", "eh", "s", "f", "ah", "l"],
    "ready": ["r", "eh", "d", "iy"],
    "complete": ["k", "ah", "m", "p", "l", "iy", "t"],
    # Common English words
    "the": ["dh", "ah"],
    "is": ["ih", "z"],
    "was": ["w", "ah", "z"],
    "are": ["aa", "r"],
    "you": ["y", "uw"],
    "and": ["ae", "n", "d"],
    "for": ["f", "ao", "r"],
    "with": ["w", "ih", "th"],
    "this": ["dh", "ih", "s"],
    "that": ["dh", "ae", "t"],
    "have": ["hh", "ae", "v"],
    "from": ["f", "r", "ah", "m"],
    "they": ["dh", "ey"],
    "been": ["b", "ih", "n"],
    "their": ["dh", "eh", "r"],
    "will": ["w", "ih", "l"],
    "would": ["w", "uh", "d"],
    "there": ["dh", "eh", "r"],
    "could": ["k", "uh", "d"],
    "people": ["p", "iy", "p", "ah", "l"],
    "other": ["ah", "dh", "er"],
    "into": ["ih", "n", "t", "uw"],
    "first": ["f", "er", "s", "t"],
    "work": ["w", "er", "k"],
    "after": ["ae", "f", "t", "er"],
    "just": ["jh", "ah", "s", "t"],
    "over": ["ow", "v", "er"],
    "think": ["th", "ih", "ng", "k"],
    "also": ["ao", "l", "s", "ow"],
    "years": ["y", "ih", "r", "z"],
    "most": ["m", "ow", "s", "t"],
    "through": ["th", "r", "uw"],
    "where": ["w", "eh", "r"],
    "should": ["sh", "uh", "d"],
    "during": ["d", "uh", "r", "ih", "ng"],
    "before": ["b", "ih", "f", "ao", "r"],
    "those": ["dh", "ow", "z"],
    "however": ["h", "aw", "eh", "v", "er"],
    "your": ["y", "ao", "r"],
    "became": ["b", "ih", "k", "ey", "m"],
    "because": ["b", "ih", "k", "ao", "z"],
    "each": ["iy", "ch"],
    "state": ["s", "t", "ey", "t"],
    "use": ["y", "uw", "z"],
    "used": ["y", "uw", "z", "d"],
    "using": ["y", "uw", "z", "ih", "ng"],
    "very": ["v", "eh", "r", "iy"],
    "good": ["g", "uh", "d"],
    "make": ["m", "ey", "k"],
    "well": ["w", "eh", "l"],
    "way": ["w", "ey"],
    "take": ["t", "ey", "k"],
    "see": ["s", "iy"],
    "know": ["n", "ow"],
    "want": ["w", "ao", "n", "t"],
    "get": ["g", "eh", "t"],
    "tell": ["t", "eh", "l"],
    "great": ["g", "r", "ey", "t"],
    "little": ["l", "ih", "t", "ah", "l"],
    "come": ["k", "ah", "m"],
    "still": ["s", "t", "ih", "l"],
    "thing": ["th", "ih", "ng"],
    "something": ["s", "ah", "m", "th", "ih", "ng"],
    "every": ["eh", "v", "r", "iy"],
    "life": ["l", "ay", "f"],
    "only": ["ow", "n", "l", "iy"],
    "back": ["b", "ae", "k"],
    "even": ["iy", "v", "ah", "n"],
    "any": ["eh", "n", "iy"],
    "being": ["b", "iy", "ih", "ng"],
    "now": ["n", "aw"],
    "part": ["p", "aa", "r", "t"],
    "another": ["ah", "n", "ah", "dh", "er"],
    "much": ["m", "ah", "ch"],
    "both": ["b", "ow", "th"],
    "between": ["b", "ih", "t", "w", "iy", "n"],
    "last": ["l", "ae", "s", "t"],
    "never": ["n", "eh", "v", "er"],
    "many": ["m", "eh", "n", "iy"],
    "then": ["dh", "eh", "n"],
    "them": ["dh", "eh", "m"],
    "these": ["dh", "iy", "z"],
    "so": ["s", "ow"],
    "such": ["s", "ah", "ch"],
    "may": ["m", "ey"],
    "its": ["ih", "t", "s"],
    "out": ["aw", "t"],
    "up": ["ah", "p"],
    "if": ["ih", "f"],
    "about": ["ah", "b", "aw", "t"],
    "when": ["w", "eh", "n"],
    "time": ["t", "ay", "m"],
    "more": ["m", "ao", "r"],
    "some": ["s", "ah", "m"],
    "her": ["hh", "er"],
    "than": ["dh", "ae", "n"],
    "two": ["t", "uw"],
    "too": ["t", "uw"],
    "can": ["k", "ae", "n"],
    "say": ["s", "ey"],
    "said": ["s", "eh", "d"],
    "did": ["d", "ih", "d"],
    "new": ["n", "y", "uw"],
    "here": ["hh", "iy", "r"],
    "call": ["k", "ao", "l"],
    "who": ["hh", "uw"],
    "oil": ["oy", "l"],
    "sit": ["s", "ih", "t"],
    "find": ["f", "ay", "n", "d"],
    "long": ["l", "ao", "ng"],
    "down": ["d", "aw", "n"],
    "day": ["d", "ey"],
    "made": ["m", "ey", "d"],
    "sound": ["s", "aw", "n", "d"],
    "year": ["y", "iy", "r"],
    "place": ["p", "l", "ey", "s"],
    "live": ["l", "ay", "v"],
    "give": ["g", "ih", "v"],
    "name": ["n", "ey", "m"],
    "sentence": ["s", "eh", "n", "t", "ah", "n", "s"],
    "man": ["m", "ae", "n"],
    "help": ["hh", "eh", "l", "p"],
    "line": ["l", "ay", "n"],
    "differ": ["d", "ih", "f", "er"],
    "turn": ["t", "er", "n"],
    "cause": ["k", "ao", "z"],
    "mean": ["m", "iy", "n"],
    "move": ["m", "uw", "v"],
    "right": ["r", "ay", "t"],
    "boy": ["b", "oy"],
    "old": ["ow", "l", "d"],
    "same": ["s", "ey", "m"],
    "does": ["d", "ah", "z"],
    "write": ["r", "ay", "t"],
    "set": ["s", "eh", "t"],
    "three": ["th", "r", "iy"],
    "air": ["eh", "r"],
    "play": ["p", "l", "ey"],
    "small": ["s", "m", "ao", "l"],
    "end": ["eh", "n", "d"],
    "put": ["p", "uh", "t"],
    "home": ["hh", "ow", "m"],
    "read": ["r", "iy", "d"],
    "hand": ["hh", "ae", "n", "d"],
    "port": ["p", "ao", "r", "t"],
    "large": ["l", "aa", "r", "jh"],
    "spell": ["s", "p", "eh", "l"],
    "add": ["ae", "d"],
    "land": ["l", "ae", "n", "d"],
    "must": ["m", "ah", "s", "t"],
    "high": ["hh", "ay"],
    "follow": ["f", "aa", "l", "ow"],
    "act": ["ae", "k", "t"],
    "why": ["w", "ay"],
    "ask": ["ae", "s", "k"],
    "men": ["m", "eh", "n"],
    "change": ["ch", "ey", "n", "jh"],
    "went": ["w", "eh", "n", "t"],
    "light": ["l", "ay", "t"],
    "kind": ["k", "ay", "n", "d"],
    "off": ["ao", "f"],
    "need": ["n", "iy", "d"],
    "house": ["hh", "aw", "s"],
    "picture": ["p", "ih", "k", "ch", "er"],
    "try": ["t", "r", "ay"],
    "us": ["ah", "s"],
    "again": ["ah", "g", "eh", "n"],
    "animal": ["ae", "n", "ah", "m", "ah", "l"],
    "point": ["p", "oy", "n", "t"],
    "mother": ["m", "ah", "dh", "er"],
    "world": ["w", "er", "l", "d"],
    "near": ["n", "iy", "r"],
    "build": ["b", "ih", "l", "d"],
    "self": ["s", "eh", "l", "f"],
    "earth": ["er", "th"],
    "father": ["f", "aa", "dh", "er"],
    "round": ["r", "aw", "n", "d"],
    "came": ["k", "ey", "m"],
    "show": ["sh", "ow"],
    "me": ["m", "iy"],
    "our": ["aw", "er"],
    "under": ["ah", "n", "d", "er"],
    "form": ["f", "ao", "r", "m"],
    "low": ["l", "ow"],
}

# Letter to phoneme mapping for unknown words
LETTER_PHONEMES = {
    "a": ["ae"],
    "b": ["b"],
    "c": ["k"],
    "d": ["d"],
    "e": ["eh"],
    "f": ["f"],
    "g": ["g"],
    "h": ["h"],
    "i": ["ih"],
    "j": ["jh"],
    "k": ["k"],
    "l": ["l"],
    "m": ["m"],
    "n": ["n"],
    "o": ["ao"],
    "p": ["p"],
    "q": ["k"],
    "r": ["r"],
    "s": ["s"],
    "t": ["t"],
    "u": ["uh"],
    "v": ["v"],
    "w": ["w"],
    "x": ["ks"],
    "y": ["y"],
    "z": ["z"],
}
